//////////////// base matrix related
// RS-QC-LDPC parameters
#define GF_M	8

#define BASE_MATRIX_C1	2
#define BASE_MATRIX_C2	2
#define BASE_MATRIX_D1	{3,3,3,3}
#define BASE_MATRIX_P_ALL {2,3,2,3}
#define BASE_MATRIX_D2	1
#define BASE_MATRIX_LAMBDA 31
#define BASE_MATRIX_P1	2
#define BASE_MATRIX_P2	3
#define BASE_MATRIX_P	(BASE_MATRIX_C1+BASE_MATRIX_C2)
#define BASE_MATRIX_PxL	(BASE_MATRIX_LAMBDA*(BASE_MATRIX_C1+BASE_MATRIX_C2))
#define CPM_SIZE		(BASE_MATRIX_LAMBDA*BASE_MATRIX_P1*BASE_MATRIX_P2)
#define BASE_CSHIFT	1

//#define BASE_MATRIX_MASKING
//#define BASE_MATRIX_LOCAL_DOWNSAMPLE	2

#define BASE_MATRIX_COL_OFFSET	 {0,BASE_MATRIX_LAMBDA,BASE_MATRIX_LAMBDA*2,BASE_MATRIX_LAMBDA*3}//,BASE_MATRIX_LAMBDA*4,BASE_MATRIX_LAMBDA*5,BASE_MATRIX_LAMBDA*6,BASE_MATRIX_LAMBDA*7}
#define N_COL_BLK	(BASE_MATRIX_P*BASE_MATRIX_LAMBDA)
//#define N_MASK_ROW	13// 64 //10
//#define N_MASK_COL	1914
//#define RANDOM_ROW_MASK
//#define RANDOM_COL_MASK
#define ROW_MASK_BEGIN 0
#define ROW_MASK_END  CPM_SIZE*2-1

////////// decoding related parmaters
#define MAX_DECODE_ITERATION 20
#define ROW_SHUFFLE
//#define INTERLACED_MINSUM


#define CNU_MAX_LLR_ABS 128
#define MAX_LLR_ABS	CNU_MAX_LLR_ABS*16*MAX_DECODE_ITERATION	//assume column degree <, or = 16

#define CNU_SCALE1	0.5
#define CNU_SCALE2  0.5
#define CNU_DEG_TH	60

//#define DEBUG_DATA
